version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: lumi_postgres
    restart: always
    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: lumi123
      POSTGRES_DB: lumi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
